# Generated by Django 5.1.4 on 2024-12-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
