# Generated by Django 5.1.4 on 2024-12-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('age', models.TextField(verbose_name='Edad permitida')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
