# Generated by Django 5.1.4 on 2024-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagen',
            field=models.ImageField(null=True, upload_to='games', verbose_name='imagen'),
        ),
    ]
