# Generated by Django 5.1.4 on 2024-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_products_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='age',
        ),
        migrations.AddField(
            model_name='products',
            name='age_max',
            field=models.IntegerField(null=True, verbose_name='Edad máxima permitida'),
        ),
        migrations.AddField(
            model_name='products',
            name='age_min',
            field=models.IntegerField(null=True, verbose_name='Edad mínima permitida'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagen',
            field=models.ImageField(null=True, upload_to='games', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Título'),
        ),
    ]
