# Generated by Django 5.1.4 on 2024-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_products_age_products_age_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Largo (m)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (m)'),
        ),
    ]
